require: rubocop-performance

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
